### ISSUE TITLE
Error on `docker exec -it servas php artisan migrate` during initial setup

### ISSUE THREAD

**Issue by jonathanlaniado** [beromir/Servas#14]
Does this look familiar to you? Not sure where things went wrong. If it helps at all, I am setting this up via a Portainer stack.

```
   Illuminate\Database\QueryException 

  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for db failed: Temporary failure in name resolution (SQL: select * from information_schema.tables where table_schema = servas_db and table_name = migrations and table_type = 'BASE TABLE')

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:742
    738▕         // If an exception occurs when attempting to run a query, we'll format the error
    739▕         // message to include the bindings with SQL, which will make this exception a
    740▕         // lot more helpful to the developer instead of just the database's errors.
    741▕         catch (Exception $e) {
  ➜ 742▕             throw new QueryException(
    743▕                 $query, $this->prepareBindings($bindings), $e
    744▕             );
    745▕         }
    746▕     }

      +36 vendor frames 
  37  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
```

**Comment by beromir** [comment]
Spontaneously i have no idea.  
Can you share your `.env` and `docker-compose.yml` file?

**Comment by jonathanlaniado** [comment]
Sure, my .env is:

```
APP_NAME=Servas
APP_ENV=production
APP_DEBUG=false
APP_URL=localhost:5347
DB_CONNECTION=mysql
DB_HOST=servasdb
DB_PORT=3306
DB_DATABASE=servas_db
DB_USERNAME=servas_db_user
DB_PASSWORD=password
```

And I don't have a YAML file, because I'm using a Portainer stack. Could that be the issue? My setup is like so:

```
version: "3.3"

services:
    servasdb:
        container_name: servasdb
        image: mariadb:10.7.3
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
        restart: unless-stopped
        network_mode: shared
        volumes:
            - $DOCKER_DIR/servas/db_data:/var/lib/mysql
        environment:
            - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
            - MARIADB_USER=${DB_USERNAME}
            - MARIADB_PASSWORD=${DB_PASSWORD}
            - MARIADB_DATABASE=${DB_DATABASE}

    servas:
        container_name: servas
        image: beromir/servas
        restart: unless-stopped
        network_mode: shared
        depends_on:
            - servasdb
        ports:
            - 5347:80
        volumes:
            - $DOCKER_DIR/servas/.env:/var/www/html/.env
```

**Comment by beromir** [comment]
I am not familiar with Portainer.
But I can imagine that the DB host is wrong, so the application can't connect to the DB.
Do you use other services with MariaDB and can you check the host settings there?

**Comment by jonathanlaniado** [comment]
I do, with Nginx Proxy Manager. See below:

```
mariadb:
    container_name: mariadb
    image: jc21/mariadb-aria:latest
    restart: unless-stopped
    network_mode: shared
    volumes:
        - $DOCKER_DIR/mariadb:/var/lib/mysql
    environment:
        - MYSQL_DATABASE=npm
        - MYSQL_PASSWORD=npm
        - MYSQL_ROOT_PASSWORD=npm
        - MYSQL_USER=npm
    entrypoint:
        - /scripts/run.sh
```

For what it's worth, I've changed the host from `servasdb` to `db` across both my .env file and in the Portainer stack. The issue persists.

.env:

```
APP_NAME=Servas
APP_ENV=production
APP_KEY=
APP_DEBUG=false
APP_URL=localhost:5347

DB_CONNECTION=mysql
DB_HOST=db
DB_PORT=3306
DB_DATABASE=servas_db
DB_USERNAME=servas_db_user
DB_PASSWORD=password
```

Stack:

```
version: "3.3"

services:
    db:
        image: mariadb:10.7.3
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
        restart: unless-stopped
        network_mode: shared
        volumes:
            - $DOCKER_DIR/servas/db_data:/var/lib/mysql
        environment:
            - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
            - MARIADB_USER=${DB_USERNAME}
            - MARIADB_PASSWORD=${DB_PASSWORD}
            - MARIADB_DATABASE=${DB_DATABASE}

    servas:
        container_name: servas
        image: beromir/servas
        restart: unless-stopped
        network_mode: shared
        depends_on:
            - db
        ports:
            - 5347:80
        volumes:
            - $DOCKER_DIR/servas/.env:/var/www/html/.env
```
