### ISSUE TITLE
Request: ARMv7/ARMv8 support

### ISSUE THREAD

**Issue by axsddlr** [beromir/Servas#17]
# Issue
Looking to use this in my self-host raspberry pi server however it does  not run

**Comment by shubhank-saxena** [comment]
+1. Would really love to have the support!

**Comment by tiagobugarin** [comment]
I managed to have it running on a Rock5B (aarch64) with Docker.
To do so I had to clone this github repository and build the docker imagem for Servas. It took 5 minutes or something like that (8-core, 16GB RAM).

My structure is:
```
./.env
./docker-compose.yml
./Github
```
The `Github` directory is a clone of this repo without modifications.
my `.env` looks like this:
```
APP_NAME=Servas
APP_ENV=production
APP_KEY=
APP_DEBUG=false
APP_URL=http://rock-5b.local:8001

SERVAS_ENABLE_REGISTRATION=true

# SQLite
DB_CONNECTION=sqlite
DB_DATABASE=/var/www/html/database/sqlite/servas.db
DB_FOREIGN_KEYS=true
```
`APP_URL` Note 1: replace `APP_URL` with your hostname;
`APP_URL` Note 2: be careful to also remove the `s` from `https`;
`APP_URL` Note 3: be careful to use the same port you will choose at `docker-compose.yml`. I am using `8001`.

My `docker-compose.yml` looks like this:
```
version: "3"
services:
  servas:
    build:
      context: ./Github/
      dockerfile: ./Dockerfile
    container_name: servas
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - ./.env:/var/www/html/.env
      - servas-db:/var/www/html/database/sqlite

volumes:
  servas-db:
```

From there you should build:
`docker compose build`

After that you can follow the official instructions to start, generate keys, restart and register the user.
