### ISSUE TITLE
Permission error when running `docker exec -it servas php artisan key:generate --force`

### ISSUE THREAD

**Issue by ibrahimbayyinah** [beromir/Servas#81]
When running `docker exec -it servas php artisan key:generate --force` I get the following error:

```php
   ErrorException 

  file_put_contents(/var/www/html/.env): Failed to open stream: Permission denied

  at vendor/laravel/framework/src/Illuminate/Foundation/Console/KeyGenerateCommand.php:109
    105▕ 
    106▕             return false;
    107▕         }
    108▕ 
  ➜ 109▕         file_put_contents($this->laravel->environmentFilePath(), $replaced);
    110▕ 
    111▕         return true;
    112▕     }
    113▕ 

      +15 vendor frames 

  16  artisan:35
      Illuminate\Foundation\Console\Kernel::handle()
```

Steps to reproduce:

1. Download [docker-compose.prod.yaml](https://github.com/beromir/Servas/blob/main/docker/docker-compose.prod.yaml) and [.env.prod.example](https://github.com/beromir/Servas/blob/main/docker/.env.prod.example) into an empty directory.
2. Rename to `docker-compose.yaml` and `.env` respectively.
3. Make edits to `.env` (see contents of both files below).
4. Run `docker-compose up -d` successfully. I get the following output:
```zsh
[+] Running 4/4
 ✔ Network servas_mariadb_default          Created                                                                       0.0s 
 ✔ Volume "servas_mariadb_servas-db-data"  Created                                                                       0.0s 
 ✔ Container servas_mariadb-db-1           Started                                                                       0.0s 
 ✔ Container servas                        Started                                                                       0.0s 
```
5. Run `docker exec -it servas php artisan key:generate --force`, which gives the above mentioned error.

I tried with the SQLite container and got the same problem.

I also tried several approaches, like:

- Clone the git repo, make the changes to `docker-compose.yaml` and `.env` and run `docker-compose up -d` from within the `docker` directory and `docker/sql-example` directory respectively.
- Change the file permissions of `.env` to `777` (to make it readable, writeable and even executable by everyone).
- Play with some values in `docker-compose.yaml` and `.env`, like: giving the full path instead of `./.env` in the `volumes` section of `docker-compose.yaml`.

Unfortunately, nothing was able to solve the problem. Reading from the error, I assume it's a problem with the `.env` file not being writeable in the container, however I am not familiar enough with containers and PHP/Laravel to be able to solve it on my own. I'd love to use this bookmarks manager as it seems to be the only one I found which meets my needs (self-hosted + nested groups). Thanks in advance for your time to help me solve this.

`.env` content:
```env
APP_NAME=Servas
APP_ENV=production
APP_KEY=
APP_DEBUG=false
APP_URL=http://localhost

SERVAS_ENABLE_REGISTRATION=true

# MySQL
DB_CONNECTION=mysql
DB_HOST=db
DB_PORT=3306
DB_DATABASE=servas_db
DB_USERNAME=servas_db_user
DB_PASSWORD=password
```
`docker-compose.yaml` (it's identical to the default):
```yaml
version: "3"

services:
  db:
    image: mariadb:10.7.3
    restart: unless-stopped
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_DATABASE}
    volumes:
      - servas-db-data:/var/lib/mysql

  servas:
    image: beromir/servas
    container_name: servas
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./.env:/var/www/html/.env

volumes:
  servas-db-data:
```

General info about my system:
- Laptop: ThinkPad X220
- Operating system: [Arch Linux](https://archlinux.org)
- Window manager/desktop environment: [Hyprland](https://hyprland.org) (a [Wayland](https://wayland.freedesktop.org/) compositor)
