### ISSUE TITLE
Registration page 404

### ISSUE THREAD

**Issue by hxck** [beromir/Servas#90]
Currently deploying this via Dockge. Visiting the main page of the site after installation shows the login form (at http://192.168.50.204:8186/login), but changing the url to /register gives me a 404. This is my compose file:

```
version: "3"
services:
  servas:
    image: beromir/servas
    container_name: servas
    restart: unless-stopped
    environment:
      - APP_NAME=Bookmarks
      - APP_ENV=production
      - APP_KEY=keyhere
      - APP_DEBUG=false
      - APP_URL=http://192.168.50.204
      - SERVAS_ENABLE_REGISTRATION=false
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/sqlite/servas.db
      - DB_FOREIGN_KEYS=true
    ports:
      - 8186:80
    volumes:
      - ./servas-db-sqlite:/var/www/html/database/sqlite
networks:
  backend:
    external: true
```

Logs show:

```
servas  | Starting Migration...
servas  | 
servas  |    INFO  Nothing to migrate.  
servas  | 
servas  | Creating caches...
servas  | 
servas  |    INFO  Configuration cached successfully.  
servas  | 
servas  | 
servas  |    INFO  Blade templates cached successfully.  
servas  | 
servas  | [06-Apr-2024 04:04:54] NOTICE: fpm is running, pid 18
servas  | [06-Apr-2024 04:04:54] NOTICE: ready to handle connections
servas  | 127.0.0.1 -  06/Apr/2024:04:05:00 +0000 "GET /index.php" 200
servas  | 127.0.0.1 -  06/Apr/2024:04:05:04 +0000 "GET /index.php" 404
```

Not really sure what I'm missing here. Any ideas?

Thanks.
