### ISSUE TITLE
docker exec command gives an error, server fails to function

### ISSUE THREAD

**Issue by driftywinds** [beromir/Servas#94]
The error: - 
```
docker exec -it servas php artisan key:generate --force

   ErrorException

  file_put_contents(/var/www/html/.env): Failed to open stream: Permission denied

  at vendor/laravel/framework/src/Illuminate/Foundation/Console/KeyGenerateCommand.php:109
    105▕
    106▕             return false;
    107▕         }
    108▕
  ➜ 109▕         file_put_contents($this->laravel->environmentFilePath(), $replaced);
    110▕
    111▕         return true;
    112▕     }
    113▕

      +15 vendor frames

  16  artisan:35
      Illuminate\Foundation\Console\Kernel::handle()

```

my docker-compose.yml file: - (using port 3002 because I use a reverse proxy with other apps)
```
version: "3"

services:
  servas:
    image: beromir/servas
    container_name: servas
    restart: unless-stopped
    ports:
      - "3002:80"
    volumes:
      - ./.env:/var/www/html/.env
      - servas-db-sqlite:/var/www/html/database/sqlite

volumes:
  servas-db-sqlite:

```

My .env file:-
```
APP_NAME=Servas
APP_ENV=production
APP_KEY=
APP_DEBUG=false
APP_URL=<my url>

SERVAS_ENABLE_REGISTRATION=true

# SQLite
DB_CONNECTION=sqlite
DB_DATABASE=/var/www/html/database/sqlite/servas.db
DB_FOREIGN_KEYS=true


```
