### ISSUE TITLE
Server error 500

### ISSUE THREAD

**Issue by diraneyya** [beromir/Servas#95]
I am curious about this software and wanted to test it locally on my computer.

To do this I used the following `.env` and `docker-compose.yaml` files:
```bash
APP_NAME=Servas
APP_ENV=production
APP_KEY=
APP_DEBUG=false
APP_URL=http://localhost:9090

SERVAS_ENABLE_REGISTRATION=true

# SQLite
DB_CONNECTION=sqlite
DB_DATABASE=/var/www/html/database/sqlite/servas.db
DB_FOREIGN_KEYS=true
```

```yaml
services:
  servas:
    image: beromir/servas
    container_name: servas
    restart: unless-stopped
    ports:
      - 9090:80
    volumes:
      - ./.env:/var/www/html/.env
      - servas-db-sqlite:/var/www/html/database/sqlite
    # labels:
    #   - "traefik.http.routers.servas.rule=Host(`Servas.docker.localhost`)"
volumes:
  servas-db-sqlite:
```

I am getting an internal server error (500) when browsing to [http://localhost:9090](http://localhost:9090):
<img width="917" alt="image" src="https://github.com/user-attachments/assets/7b4ec3fb-ab39-4120-8ce4-06befee7e7b8">

Logs aren't showing much, either:
<img width="677" alt="image" src="https://github.com/user-attachments/assets/cfcf722e-b5eb-48d1-9ca0-f20ab424f145">
